
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

//Esto es el contenedor de toda la aplicación
export default function RootLayout({ children }) {
    return <html>
         <head>
         <title>Mi aplicación</title> 
           </head>

           <body>
           <nav>
                <h1>Navegador</h1>
                <ul>
                    <li>Home</li>
                    <li>Tienda</li>
                    <li>Categoria</li>

                </ul> 
            </nav>  
            {children} 
           </body>
    </html>
        
    
}